export const PLAYERS = {
    KAMIL: 'KAMIL',
    MARWIN: 'MARWIN',
    KARMEL: 'KARMEL',
    LUKASZ: 'LUKASZ'
};

export const TEAMS = {
    LEGIA_WARSZAWA: 'LEGIA_WARSZAWA',
    POGON_SZCZECIN: 'POGON_SZCZECIN',
    SLASK_WROCLAW: 'SLASK_WROCLAW',
    ZAGLEBIE_LUBIN: 'ZAGLEBIE_LUBIN',
    GORNIK_ZABRZE: 'GORNIK_ZABRZE',
    WARTA_POZNAN: 'WARTA_POZNAN',
    LECH_POZNAN: 'LECH_POZNAN',
    WISLA_KRAKOW: 'WISLA_KRAKOW',
    CRACOVIA: 'CRACOVIA',
    RAKOW_CZESTOCHOWA: 'RAKOW_CZESTOCHOWA',
    STAL_MIELEC: 'STAL_MIELEC',
    JAGIELLONIA_BIALYSTOK: 'JAGIELLONIA_BIALYSTOK',
    LECHIA_GDANSK: 'LECHIA_GDANSK',
    WISLA_PLOCK: 'WISLA_PLOCK',
    PODBESKIDZIE: 'PODBESKIDZIE',
    PIAST_GLIWICE: 'PIAST_GLIWICE'
};